services:
  tgbot:
    build: .
    restart: unless-stopped
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN:?}
      TG_BOT_NAME: ${TG_BOT_NAME:-TGBot}
      TG_BOT_USERNAME: ${TG_BOT_USERNAME:-TGBot}
    volumes:
      - tgbot-data:/app/data
    labels:
      - "traefik.enable=false"
